# アボカドが有機なのか無機なのか予測する

In [2]:
import pandas as pd

df = pd.read_csv('avocado.csv', index_col ='Date', parse_dates=['Date'])

In [3]:
df.head(3)

,Unnamed: 0,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
Date,,,,,,,,,,,,,
2015-12-27,0,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany
2015-12-20,1,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany
2015-12-13,2,0.93,118220.22,794.70,109149.67,130.50,8145.35,8042.21,103.14,0.0,conventional,2015,Albany

In [8]:
obj_col = 'type'
df[obj_col].value_counts()

0    9126
1    9123
Name: type, dtype: int64

In [9]:
#ラベルを整数に変換

#行要素, 列要素 locはdataframeのlocation（変える部分を指定している）
#obj_colがconventionalなら0, organaicなら1
df.loc[df[obj_col]=='conventional',obj_col] = 0
df.loc[df[obj_col]=='organic',obj_col] = 1

#目的変数の型変換
df.loc[:,obj_col]=df.loc[:, obj_col].astype(int)

/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/pandas/core/ops.py:798: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  result = getattr(x, name)(y)

TypeError: invalid type comparison

In [10]:
exp_col = ['AveragePrice', 
           'Total Volume', 
           '4046', 
           '4225', 
           '4770', 
           'Total Bags', 
           'Small Bags', 
           'Large Bags', 
           'XLarge Bags']

In [11]:
len(exp_col)

9

In [12]:
df[exp_col].values

array([[1.3300000e+00, 6.4236620e+04, 1.0367400e+03, ..., 8.6036200e+03,
        9.3250000e+01, 0.0000000e+00],
       [1.3500000e+00, 5.4876980e+04, 6.7428000e+02, ..., 9.4080700e+03,
        9.7490000e+01, 0.0000000e+00],
       [9.3000000e-01, 1.1822022e+05, 7.9470000e+02, ..., 8.0422100e+03,
        1.0314000e+02, 0.0000000e+00],
       ...,
       [1.8700000e+00, 1.3766760e+04, 1.1919200e+03, ..., 9.3518000e+03,
        4.2310000e+01, 0.0000000e+00],
       [1.9300000e+00, 1.6205220e+04, 1.5276300e+03, ..., 1.0919540e+04,
        5.0000000e+01, 0.0000000e+00],
       [1.6200000e+00, 1.7489580e+04, 2.8947700e+03, ..., 1.1988140e+04,
        2.6010000e+01, 0.0000000e+00]])

In [13]:
df[obj_col].values

array([0, 0, 0, ..., 1, 1, 1])

In [14]:
train_df = df.loc[:'2017',:]
test_df = df.loc['2018':,:]

In [15]:
train_df

,Unnamed: 0,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
Date,,,,,,,,,,,,,
2015-12-27,0,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.00,0,2015,Albany
2015-12-20,1,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.00,0,2015,Albany
2015-12-13,2,0.93,118220.22,794.70,109149.67,130.50,8145.35,8042.21,103.14,0.00,0,2015,Albany
2015-12-06,3,1.08,78992.15,1132.00,71976.41,72.58,5811.16,5677.40,133.76,0.00,0,2015,Albany
2015-11-29,4,1.28,51039.60,941.48,43838.39,75.78,6183.95,5986.26,197.69,0.00,0,2015,Albany
2015-11-22,5,1.26,55979.78,1184.27,48067.99,43.61,6683.91,6556.47,127.44,0.00,0,2015,Albany
2015-11-15,6,0.99,83453.76,1368.92,73672.72,93.26,8318.86,8196.81,122.05,0.00,0,2015,Albany
2015-11-08,7,0.98,109428.33,703.75,101815.36,80.00,6829.22,6266.85,562.37,0.00,0,2015,Albany
2015-11-01,8,1.02,99811.42,1022.15,87315.57,85.34,11388.36,11104.53,283.83,0.00,0,2015,Albany
2015-10-25,9,1.07,74338.76,842.40,64757.44,113.00,8625.92,8061.47,564.45,0.00,0,2015,Albany
2015-10-18,10,1.12,84843.44,924.86,75595.85,117.07,8205.66,7877.86,327.80,0.00,0,2015,Albany
2015-10-11,11,1.28,64489.17,1582.03,52677.92,105.32,10123.90,9866.27,257.63,0.00,0,2015,Albany
2015-10-04,12,1.31,61007.10,2268.32,49880.67,101.36,8756.75,8379.98,376.77,0.00,0,2015,Albany
2015-09-27,13,0.99,106803.39,1204.88,99409.21,154.84,6034.46,5888.87,145.59,0.00,0,2015,Albany
2015-09-20,14,1.33,69759.01,1028.03,59313.12,150.50,9267.36,8489.10,778.26,0.00,0,2015,Albany
2015-09-13,15,1.28,76111.27,985.73,65696.86,142.00,9286.68,8665.19,621.49,0.00,0,2015,Albany
2015-09-06,16,1.11,99172.96,879.45,90062.62,240.79,7990.10,7762.87,227.23,0.00,0,2015,Albany
2015-08-30,17,1.07,105693.84,689.01,94362.67,335.43,10306.73,10218.93,87.80,0.00,0,2015,Albany
2015-08-23,18,1.34,79992.09,733.16,67933.79,444.78,10880.36,10745.79,134.57,0.00,0,2015,Albany
2015-08-16,19,1.33,80043.78,539.65,68666.01,394.90,10443.22,10297.68,145.54,0.00,0,2015,Albany
2015-08-09,20,1.12,111140.93,584.63,100961.46,368.95,9225.89,9116.34,109.55,0.00,0,2015,Albany
2015-08-02,21,1.45,75133.10,509.94,62035.06,741.08,11847.02,11768.52,78.50,0.00,0,2015,Albany
2015-07-26,22,1.11,106757.10,648.75,91949.05,966.61,13192.69,13061.53,131.16,0.00,0,2015,Albany
2015-07-19,23,1.26,96617.00,1042.10,82049.40,2238.02,11287.48,11103.49,183.99,0.00,0,2015,Albany
2015-07-12,24,1.05,124055.31,672.25,94693.52,4257.64,24431.90,24290.08,108.49,33.33,0,2015,Albany
2015-07-05,25,1.35,109252.12,869.45,72600.55,5883.16,29898.96,29663.19,235.77,0.00,0,2015,Albany
2015-06-28,26,1.37,89534.81,664.23,57545.79,4662.71,26662.08,26311.76,350.32,0.00,0,2015,Albany
2015-06-21,27,1.27,104849.39,804.01,76688.55,5481.18,21875.65,21662.00,213.65,0.00,0,2015,Albany
2015-06-14,28,1.32,89631.30,850.58,55400.94,4377.19,29002.59,28343.14,659.45,0.00,0,2015,Albany
2015-06-07,29,1.07,122743.06,656.71,99220.82,90.32,22775.21,22314.99,460.22,0.00,0,2015,Albany
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-08-06,21,1.78,15242.53,2134.24,4592.66,331.60,8184.03,8171.22,12.81,0.00,1,2017,WestTexNewMexico
2017-07-30,22,1.67,17633.69,2618.13,3169.61,1056.54,10789.41,10733.97,55.44,0.00,1,2017,WestTexNewMexico
2017-07-23,23,1.60,19144.32,1832.11,4752.03,1914.09,10646.09,10577.95,68.14,0.00,1,2017,WestTexNewMexico
2017-07-16,24,1.60,19126.81,1763.86,4382.01,2211.74,10769.20,10652.21,116.99,0.00,1,2017,WestTexNewMexico
2017-07-09,25,1.65,18244.09,2295.76,3701.18,38.67,12208.48,11637.39,571.09,0.00,1,2017,WestTexNewMexico
2017-07-02,26,1.59,20486.25,2454.99,3470.63,0.00,14560.63,10390.44,4170.19,0.00,1,2017,WestTexNewMexico
2017-06-11,27,1.66,21170.11,3042.11,3588.46,0.00,14539.54,7757.19,6782.35,0.00,1,2017,WestTexNewMexico
2017-06-04,28,1.59,25886.30,3305.88,3706.22,0.00,18874.20,8654.49,10219.71,0.00,1,2017,WestTexNewMexico
2017-05-28,29,1.65,18798.80,2703.95,4148.35,11.11,11935.39,5244.73,6690.66,0.00,1,2017,WestTexNewMexico
2017-05-21,30,1.73,16899.03,3988.80,5269.43,16.64,7624.16,4373.14,3251.02,0.00,1,2017,WestTexNewMexico
2017-05-14,31,1.77,18131.79,5410.04,5406.61,0.00,7315.14,4198.56,3116.58,0.00,1,2017,WestTexNewMexico
2017-05-07,32,1.74,16697.08,3986.53,4485.20,22.54,8202.81,5333.82,2868.99,0.00,1,2017,WestTexNewMexico
2017-04-30,33,1.76,15686.98,1763.36,5824.80,2.82,8096.00,4515.13,3580.87,0.00,1,2017,WestTexNewMexico
2017-04-23,34,1.63,19234.05,1758.80,7535.06,16.99,9923.20,5530.18,4393.02,0.00,1,2017,WestTexNewMexico
2017-04-16,35,1.23,29765.63,2233.24,4805.48,17.29,22709.62,21441.99,1267.63,0.00,1,2017,WestTexNewMexico
2017-04-09,36,1.19,30499.28,2386.19,3749.72,34.72,24328.65,24193.63,135.02,0.00,1,2017,WestTexNewMexico
2017-04-02,37,1.04,28803.50,2551.72,2586.16,11.61,23654.01,23267.01,387.00,0.00,1,2017,WestTexNewMexico
2017-03-26,38,1.11,32073.43,3041.33,3451.21,66.76,25514.13,25191.62,322.51,0.00,1,2017,WestTexNewMexico
2017-03-19,39,1.11,26767.63,4255.75,3855.69,11.67,18644.52,13278.06,5366.46,0.00,1,2017,WestTexNewMexico
2017-03-12,40,1.15,26522.49,3289.27,3877.22,26.38,19329.62,17880.59,1449.03,0.00,1,2017,WestTexNewMexico
2017-03-05,41,1.23,24969.30,2292.42,4876.69,52.82,17747.37,17114.89,632.48,0.00,1,2017,WestTexNewMexico
2017-02-26,42,1.16,39054.83,3021.26,15568.68,11.77,20453.12,20299.52,153.60,0.00,1,2017,WestTexNewMexico
2017-02-19,43,1.24,25777.67,2208.27,5671.84,35.60,17861.96,17821.27,40.69,0.00,1,2017,WestTexNewMexico
2017-02-12,44,1.40,28191.45,2248.71,9177.71,37.92,16727.11,16570.14,156.97,0.00,1,2017,WestTexNewMexico
2017-02-05,45,1.31,21376.32,2161.38,5646.59,11.84,13556.51,13372.37,184.14,0.00,1,2017,WestTexNewMexico
2017-01-29,46,1.30,17839.37,1486.34,4498.48,26.12,11828.43,11821.76,6.67,0.00,1,2017,WestTexNewMexico
2017-01-22,47,1.21,16430.64,1413.93,2820.53,20.25,12175.93,12073.07,102.86,0.00,1,2017,WestTexNewMexico
2017-01-15,48,1.19,17014.23,1203.87,2904.22,23.07,12883.07,12476.57,406.50,0.00,1,2017,WestTexNewMexico
2017-01-08,49,1.18,14375.39,1327.98,2617.20,5.75,10424.46,10283.85,140.61,0.00,1,2017,WestTexNewMexico
2017-01-01,50,1.28,15307.87,867.66,3434.02,37.30,10968.89,10815.88,153.01,0.00,1,2017,WestTexNewMexico

In [16]:
X_train = train_df.loc[:'2017', exp_col].values   #訓練　説明変数
y_train = train_df.loc[:'2017', obj_col].values   #訓練　目的変数（ラベル）

X_test = test_df.loc['2018':, exp_col].values     #テスト　説明変数
y_test = test_df.loc['2018':, obj_col].values     #テスト　目的変数（ラベル）

In [17]:
test_df.loc[:,obj_col].value_counts()

1    648
0    648
Name: type, dtype: int64

## SVMで分類

In [18]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
#標準化させるために訓練データだけで平均と分散を計算
scaler.fit(X_train)
#訓練データ，テストデータを標準化する．
X_train = scaler.transform(X_train)
X_test  = scaler.transform(X_test)

In [19]:
X_train

array([[-0.19679289, -0.22770438, -0.23101154, ..., -0.23273316,
        -0.22591171, -0.1727193 ],
       [-0.14786775, -0.23047267, -0.23130308, ..., -0.23160694,
        -0.22589297, -0.1727193 ],
       [-1.17529573, -0.21173772, -0.23120623, ..., -0.23351912,
        -0.22586799, -0.1727193 ],
       ...,
       [-0.53926889, -0.24167129, -0.23087712, ..., -0.2273111 ,
        -0.22452708, -0.1727193 ],
       [-0.56373146, -0.24245177, -0.23077729, ..., -0.23038087,
        -0.22570237, -0.1727193 ],
       [-0.31910575, -0.24217597, -0.23114754, ..., -0.22963604,
        -0.22564756, -0.1727193 ]])

In [20]:
from sklearn.svm import SVC

clf = SVC(class_weight='balanced',random_state=0)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

In [21]:
from sklearn.metrics import classification_report

print('平均予測精度 : {}\n'.format(clf.score(X_test, y_test)))
print(classification_report(y_test, y_pred,target_names=['conventional','organic']))

平均予測精度 : 0.9483024691358025

              precision    recall  f1-score   support

conventional       0.97      0.92      0.95       648
     organic       0.93      0.98      0.95       648

 avg / total       0.95      0.95      0.95      1296

## Kerasのニューラルネットを使って予測

In [59]:
from keras import models
from keras import layers

network = models.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape=(len(exp_col),))) 
network.add(layers.Dense(10, activation='relu'))
network.add(layers.Dense(10, activation='relu'))
network.add(layers.Dense(10, activation='relu'))
network.add(layers.Dense(2, activation='softmax'))

In [60]:
## ネットワークのコンパイル
## rmsprop = AdaGrad + 勾配の二乗の指数移動平均

network.compile(optimizer='Adam', 
                loss = 'binary_crossentropy',   #カテゴリカル変数（独立しているデータ（１・２・３など）離散的）
                metrics=['accuracy'])

In [24]:
y_train.shape

(16953,)

In [45]:
## ラベルエンコード => one-hot エンコード

from keras.utils import to_categorical

train_labels = to_categorical(y_train)
test_labels = to_categorical(y_test)

In [38]:
train_labels.shape

(16953, 2)

In [39]:
test_labels

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [0., 1.],
       [0., 1.],
       [0., 1.]])

In [61]:
network.fit(X_train, train_labels, epochs=100, batch_size=1024)

Epoch 1/100
16953/16953 [==============================] - 0s 28us/step - loss: 0.6368 - acc: 0.7761
Epoch 2/100
16953/16953 [==============================] - 0s 5us/step - loss: 0.4896 - acc: 0.8225
Epoch 3/100
16953/16953 [==============================] - 0s 5us/step - loss: 0.3866 - acc: 0.8289
Epoch 4/100
16953/16953 [==============================] - 0s 5us/step - loss: 0.3539 - acc: 0.8408
Epoch 5/100
16953/16953 [==============================] - 0s 5us/step - loss: 0.3193 - acc: 0.8594
Epoch 6/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.2783 - acc: 0.8794
Epoch 7/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.2308 - acc: 0.9113
Epoch 8/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.1954 - acc: 0.9316
Epoch 9/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.1747 - acc: 0.9372
Epoch 10/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.1628 - acc: 0.9375
Epoch 11/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.1578 - acc: 0.9371
Epoch 12/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.1483 - acc: 0.9423
Epoch 13/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.1421 - acc: 0.9443
Epoch 14/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.1397 - acc: 0.9451
Epoch 15/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.1354 - acc: 0.9468
Epoch 16/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.1321 - acc: 0.9478
Epoch 17/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.1281 - acc: 0.9502
Epoch 18/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.1273 - acc: 0.9505
Epoch 19/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.1226 - acc: 0.9532
Epoch 20/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.1201 - acc: 0.9542
Epoch 21/100
16953/16953 [==============================] - 0s 5us/step - loss: 0.1175 - acc: 0.9560
Epoch 22/100
16953/16953 [==============================] - 0s 5us/step - loss: 0.1159 - acc: 0.9569
Epoch 23/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.1146 - acc: 0.9562
Epoch 24/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.1136 - acc: 0.9563
Epoch 25/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.1111 - acc: 0.9577
Epoch 26/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.1115 - acc: 0.9570
Epoch 27/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.1090 - acc: 0.9586
Epoch 28/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.1067 - acc: 0.9592
Epoch 29/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.1066 - acc: 0.9595
Epoch 30/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.1049 - acc: 0.9597
Epoch 31/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.1037 - acc: 0.9597
Epoch 32/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.1041 - acc: 0.9592
Epoch 33/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.1039 - acc: 0.9591
Epoch 34/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.1009 - acc: 0.9610
Epoch 35/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.1009 - acc: 0.9604
Epoch 36/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.1021 - acc: 0.9594
Epoch 37/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.1025 - acc: 0.9590
Epoch 38/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.1006 - acc: 0.9607
Epoch 39/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.1012 - acc: 0.9603
Epoch 40/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.0982 - acc: 0.9620
Epoch 41/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.0970 - acc: 0.9615
Epoch 42/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.0956 - acc: 0.9624
Epoch 43/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.0956 - acc: 0.9614
Epoch 44/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.0932 - acc: 0.9625
Epoch 45/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.0925 - acc: 0.9636
Epoch 46/100
16953/16953 [==============================] - 0s 5us/step - loss: 0.0931 - acc: 0.9626
Epoch 47/100
16953/16953 [==============================] - 0s 5us/step - loss: 0.0940 - acc: 0.9623
Epoch 48/100
16953/16953 [==============================] - 0s 5us/step - loss: 0.0949 - acc: 0.9616
Epoch 49/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.0915 - acc: 0.9633
Epoch 50/100
16953/16953 [==============================] - 0s 5us/step - loss: 0.0892 - acc: 0.9638
Epoch 51/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.0900 - acc: 0.9631
Epoch 52/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.0900 - acc: 0.9640
Epoch 53/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.0920 - acc: 0.9632
Epoch 54/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.0900 - acc: 0.9624
Epoch 55/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.0873 - acc: 0.9651
Epoch 56/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.0858 - acc: 0.9660
Epoch 57/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.0885 - acc: 0.9638
Epoch 58/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.0858 - acc: 0.9653
Epoch 59/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.0838 - acc: 0.9660
Epoch 60/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.0839 - acc: 0.9655
Epoch 61/100
16953/16953 [==============================] - 0s 5us/step - loss: 0.0842 - acc: 0.9661
Epoch 62/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.0846 - acc: 0.9640
Epoch 63/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.0841 - acc: 0.9657
Epoch 64/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.0864 - acc: 0.9640
Epoch 65/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.0835 - acc: 0.9661
Epoch 66/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.0802 - acc: 0.9680
Epoch 67/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.0813 - acc: 0.9664
Epoch 68/100
16953/16953 [==============================] - 0s 5us/step - loss: 0.0800 - acc: 0.9673
Epoch 69/100
16953/16953 [==============================] - 0s 5us/step - loss: 0.0807 - acc: 0.9664
Epoch 70/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.0803 - acc: 0.9666
Epoch 71/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.0785 - acc: 0.9673
Epoch 72/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.0793 - acc: 0.9670
Epoch 73/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.0813 - acc: 0.9650
Epoch 74/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.0772 - acc: 0.9677
Epoch 75/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.0754 - acc: 0.9692
Epoch 76/100
16953/16953 [==============================] - 0s 5us/step - loss: 0.0748 - acc: 0.9696
Epoch 77/100
16953/16953 [==============================] - 0s 5us/step - loss: 0.0779 - acc: 0.9677
Epoch 78/100
16953/16953 [==============================] - 0s 5us/step - loss: 0.0763 - acc: 0.9680
Epoch 79/100
16953/16953 [==============================] - 0s 5us/step - loss: 0.0755 - acc: 0.9687
Epoch 80/100
16953/16953 [==============================] - 0s 5us/step - loss: 0.0739 - acc: 0.9702
Epoch 81/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.0744 - acc: 0.9694
Epoch 82/100

16953/16953 [==============================] - 0s 4us/step - loss: 0.0734 - acc: 0.9696
Epoch 83/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.0745 - acc: 0.9688
Epoch 84/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.0741 - acc: 0.9690
Epoch 85/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.0734 - acc: 0.9703
Epoch 86/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.0702 - acc: 0.9720
Epoch 87/100
16953/16953 [==============================] - 0s 5us/step - loss: 0.0706 - acc: 0.9720
Epoch 88/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.0708 - acc: 0.9702
Epoch 89/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.0710 - acc: 0.9716
Epoch 90/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.0707 - acc: 0.9704
Epoch 91/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.0716 - acc: 0.9720
Epoch 92/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.0696 - acc: 0.9727
Epoch 93/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.0700 - acc: 0.9719
Epoch 94/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.0684 - acc: 0.9729
Epoch 95/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.0680 - acc: 0.9723
Epoch 96/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.0661 - acc: 0.9742
Epoch 97/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.0671 - acc: 0.9732
Epoch 98/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.0655 - acc: 0.9742
Epoch 99/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.0676 - acc: 0.9733
Epoch 100/100
16953/16953 [==============================] - 0s 4us/step - loss: 0.0660 - acc: 0.9736

In [29]:
X_train

array([[-0.19679289, -0.22770438, -0.23101154, ..., -0.23273316,
        -0.22591171, -0.1727193 ],
       [-0.14786775, -0.23047267, -0.23130308, ..., -0.23160694,
        -0.22589297, -0.1727193 ],
       [-1.17529573, -0.21173772, -0.23120623, ..., -0.23351912,
        -0.22586799, -0.1727193 ],
       ...,
       [-0.53926889, -0.24167129, -0.23087712, ..., -0.2273111 ,
        -0.22452708, -0.1727193 ],
       [-0.56373146, -0.24245177, -0.23077729, ..., -0.23038087,
        -0.22570237, -0.1727193 ],
       [-0.31910575, -0.24217597, -0.23114754, ..., -0.22963604,
        -0.22564756, -0.1727193 ]])

In [62]:
test_loss, test_acc = network.evaluate(X_test, test_labels)

1296/1296 [==============================] - 0s 182us/step

In [63]:
print('test_acc:', test_acc)

test_acc: 0.9837962962962963

In [65]:
y_train_pred =network.predict(X_train)

In [68]:
from sklearn.ensemble import RandomForestClassifier

clf_rf = RandomForestClassifier()
clf_rf.fit(X_train, train_labels)
y_pred = clf_rf.predict(X_test)


# Feature Importance
fti = clf_rf.feature_importances_   

print('Feature Importances:')
for i, feat in enumerate(exp_col):
    print('\t{0:20s} : {1:>.6f}'.format(feat, fti[i]))

Feature Importances:
	AveragePrice         : 0.053101
	Total Volume         : 0.197943
	4046                 : 0.052307
	4225                 : 0.327612
	4770                 : 0.188854
	Total Bags           : 0.034523
	Small Bags           : 0.080144
	Large Bags           : 0.018172
	XLarge Bags          : 0.047344